# Generated by Django 2.2.21 on 2021-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polygon',
            unique_together={('lat', 'lng')},
        ),
    ]
